FROM node:18-alpine
ENV CI=true

WORKDIR /var/www/html/docker-app/client

COPY ./package.json ./
RUN npm install
COPY ./ ./

CMD ["sh", "-c", "npm run lint:fix && npm run lint && npm run prettify && npm run start"]