name: checks
on:
  pull_request:
  push:
    branches:
      - master

env:
  CLIENT_IMAGE_VERSION: 2.0.1
  API_IMAGE_VERSION: 2.0.1
  WORKER_IMAGE_VERSION: 2.0.1

jobs:
  prepare-to-deploy:
    name: Prepare to deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Client Test App
        run: docker build -t rzldevdoc/client-test -f ./client/Dockerfile.dev ./client
      - name: Test Client Test App
        run: docker run --rm -e CI=true rzldevdoc/client-test sh -c "npm run test && npm run lint"
      - name: Build Client Image
        run: docker build -t rzldevdoc/multi-client:latest -t rzldevdoc/multi-client:${{ env.CLIENT_IMAGE_VERSION }} -f ./client/Dockerfile ./client
      - name: Push Client Image Latest
        run: docker push rzldevdoc/multi-client:latest
      - name: Push Client Image with specific version
        run: docker push rzldevdoc/multi-client:${{ env.CLIENT_IMAGE_VERSION }}
      - name: Build API Image
        run: docker build -t rzldevdoc/multi-api:latest -t rzldevdoc/multi-api:${{ env.API_IMAGE_VERSION }} -f ./server/Dockerfile ./server
      - name: Push API Image Latest
        run: docker push rzldevdoc/multi-api:latest
      - name: Push API Image with specific version
        run: docker push rzldevdoc/multi-api:${{ env.API_IMAGE_VERSION }}
      - name: Build Worker Image
        run: docker build -t rzldevdoc/multi-worker:latest -t rzldevdoc/multi-worker:${{ env.WORKER_IMAGE_VERSION }} -f ./worker/Dockerfile ./worker
      - name: Push Worker Image Latest
        run: docker push rzldevdoc/multi-worker:latest
      - name: Push Worker Image with specific version
        run: docker push rzldevdoc/multi:worker:${{ env.WORKER_IMAGE_VERSION }}
